from django.urls import path
from . import views

urlpatterns = [
    path('dashboard/', views.master_dashboard, name='master_dashboard'),
    path('bookings/', views.master_bookings, name='master_bookings'),
    path('cancel-booking/<int:booking_id>/',
         views.cancel_booking, name='master_cancel_booking'),
    path('reschedule-booking/<int:booking_id>/',
         views.reschedule_booking, name='master_reschedule_booking'),
    path('responses/', views.master_responses, name='master_responses'),
    path('update-response/<int:response_id>/',
         views.update_response, name='update_response'),
    path('cancel-response/<int:response_id>/',
         views.cancel_response, name='cancel_response'),
    path('clients/', views.master_clients, name='master_clients'),
    path('portfolio/', views.master_portfolio, name='master_portfolio'),
    path('portfolio/add/', views.add_portfolio_item, name='add_portfolio_item'),
    path('portfolio/delete/<int:item_id>/',
         views.delete_portfolio_item, name='delete_portfolio_item'),
    path('reviews/', views.master_reviews, name='master_reviews'),
    path('list/', views.masters_list, name='masters_list'),
    path('complete-profile/', views.complete_profile,
         name='master_complete_profile'),
    path('update-profile/', views.update_profile, name='master_update_profile'),
    path('services/save/', views.save_master_services,
         name='save_master_services'),
    path('profile/<int:master_id>/', views.master_public_profile,
         name='master_public_profile'),
    path('profile/<int:master_id>/review/',
         views.add_master_review, name='add_master_review'),
    path('schedule/', views.master_schedule, name='master_schedule'),
    path('schedule/add/', views.add_schedule_slot, name='add_schedule_slot'),
    path('schedule/delete/<int:slot_id>/',
         views.delete_schedule_slot, name='delete_schedule_slot'),

    path('profile/<int:master_id>/book/',
         views.book_master, name='book_master'),
    path('profile/<int:master_id>/book/create/',
         views.create_master_booking, name='create_master_booking'),
]
