# Generated by Django 5.2.10 on 2026-03-19 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0002_masterprofile_created_at_masterprofile_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='masterprofile',
            options={'verbose_name': 'Профиль мастера', 'verbose_name_plural': 'Профили мастеров'},
        ),
        migrations.AddField(
            model_name='masterprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='masters/avatars/', verbose_name='Аватар'),
        ),
        migrations.AddField(
            model_name='masterprofile',
            name='is_profile_completed',
            field=models.BooleanField(default=False, verbose_name='Профиль заполнен'),
        ),
        migrations.AlterField(
            model_name='masterprofile',
            name='address_text',
            field=models.CharField(max_length=255, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='masterprofile',
            name='bio',
            field=models.TextField(blank=True, null=True, verbose_name='О себе'),
        ),
        migrations.AlterField(
            model_name='masterprofile',
            name='display_name',
            field=models.CharField(max_length=255, verbose_name='Имя или название студии'),
        ),
        migrations.AlterField(
            model_name='masterprofile',
            name='is_approved',
            field=models.BooleanField(default=False, verbose_name='Подтвержден'),
        ),
        migrations.AlterModelTable(
            name='masterprofile',
            table='masters_masterprofile',
        ),
    ]
