# Generated by Django 5.2.10 on 2026-04-23 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0004_portfolio'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterprofile',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='masterprofile',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
